import {getPhoto} from './data.js';
getPhoto();
import {getImageFragment} from './picture.js';
getImageFragment();
import {openModal, closeModal} from './form.js';
openModal();
closeModal();
import {changeSize, disableButton, changeEffect} from './photo-editor.js';
changeSize();
disableButton();
changeEffect();
import {moveSlider} from './slider.js';
moveSlider();
